// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Payloads/rpc_handshake.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Neon.Rpc.Messages.Proto {

  /// <summary>Holder for reflection information generated from Payloads/rpc_handshake.proto</summary>
  internal static partial class RpcHandshakeReflection {

    #region Descriptor
    /// <summary>File descriptor for Payloads/rpc_handshake.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RpcHandshakeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxQYXlsb2Fkcy9ycGNfaGFuZHNoYWtlLnByb3RvEghuZW9uLnJwYyJyChhS",
            "cGNIYW5kc2hha2VSZXF1ZXN0UHJvdG8SGAoQcHJvdG9jb2xfdmVyc2lvbhgB",
            "IAEoBRI8ChJlbmNyeXB0aW9uX3JlcXVlc3QYAiABKAsyIC5uZW9uLnJwYy5F",
            "bmNyeXB0aW9uUmVxdWVzdFByb3RvIlsKGVJwY0hhbmRzaGFrZVJlc3BvbnNl",
            "UHJvdG8SPgoTZW5jcnlwdGlvbl9yZXNwb25zZRgBIAEoCzIhLm5lb24ucnBj",
            "LkVuY3J5cHRpb25SZXNwb25zZVByb3RvIm8KFkVuY3J5cHRpb25SZXF1ZXN0",
            "UHJvdG8SHAoUZW5jcnlwdGlvbl9hbGdvcml0aG0YASABKAkSHgoWa2V5X2V4",
            "Y2hhbmdlX2FsZ29yaXRobRgCIAEoCRIXCg9jbGllbnRfa2V5X2RhdGEYAyAB",
            "KAwiMgoXRW5jcnlwdGlvblJlc3BvbnNlUHJvdG8SFwoPc2VydmVyX2tleV9k",
            "YXRhGAEgASgMQhqqAhdOZW9uLlJwYy5NZXNzYWdlcy5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Rpc.Messages.Proto.RpcHandshakeRequestProto), global::Neon.Rpc.Messages.Proto.RpcHandshakeRequestProto.Parser, new[]{ "ProtocolVersion", "EncryptionRequest" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Rpc.Messages.Proto.RpcHandshakeResponseProto), global::Neon.Rpc.Messages.Proto.RpcHandshakeResponseProto.Parser, new[]{ "EncryptionResponse" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Rpc.Messages.Proto.EncryptionRequestProto), global::Neon.Rpc.Messages.Proto.EncryptionRequestProto.Parser, new[]{ "EncryptionAlgorithm", "KeyExchangeAlgorithm", "ClientKeyData" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Rpc.Messages.Proto.EncryptionResponseProto), global::Neon.Rpc.Messages.Proto.EncryptionResponseProto.Parser, new[]{ "ServerKeyData" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  internal sealed partial class RpcHandshakeRequestProto : pb::IMessage<RpcHandshakeRequestProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RpcHandshakeRequestProto> _parser = new pb::MessageParser<RpcHandshakeRequestProto>(() => new RpcHandshakeRequestProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RpcHandshakeRequestProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Rpc.Messages.Proto.RpcHandshakeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RpcHandshakeRequestProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RpcHandshakeRequestProto(RpcHandshakeRequestProto other) : this() {
      protocolVersion_ = other.protocolVersion_;
      encryptionRequest_ = other.encryptionRequest_ != null ? other.encryptionRequest_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RpcHandshakeRequestProto Clone() {
      return new RpcHandshakeRequestProto(this);
    }

    /// <summary>Field number for the "protocol_version" field.</summary>
    public const int ProtocolVersionFieldNumber = 1;
    private int protocolVersion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ProtocolVersion {
      get { return protocolVersion_; }
      set {
        protocolVersion_ = value;
      }
    }

    /// <summary>Field number for the "encryption_request" field.</summary>
    public const int EncryptionRequestFieldNumber = 2;
    private global::Neon.Rpc.Messages.Proto.EncryptionRequestProto encryptionRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Neon.Rpc.Messages.Proto.EncryptionRequestProto EncryptionRequest {
      get { return encryptionRequest_; }
      set {
        encryptionRequest_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RpcHandshakeRequestProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RpcHandshakeRequestProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ProtocolVersion != other.ProtocolVersion) return false;
      if (!object.Equals(EncryptionRequest, other.EncryptionRequest)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ProtocolVersion != 0) hash ^= ProtocolVersion.GetHashCode();
      if (encryptionRequest_ != null) hash ^= EncryptionRequest.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ProtocolVersion != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ProtocolVersion);
      }
      if (encryptionRequest_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(EncryptionRequest);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ProtocolVersion != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ProtocolVersion);
      }
      if (encryptionRequest_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(EncryptionRequest);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ProtocolVersion != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ProtocolVersion);
      }
      if (encryptionRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EncryptionRequest);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RpcHandshakeRequestProto other) {
      if (other == null) {
        return;
      }
      if (other.ProtocolVersion != 0) {
        ProtocolVersion = other.ProtocolVersion;
      }
      if (other.encryptionRequest_ != null) {
        if (encryptionRequest_ == null) {
          EncryptionRequest = new global::Neon.Rpc.Messages.Proto.EncryptionRequestProto();
        }
        EncryptionRequest.MergeFrom(other.EncryptionRequest);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ProtocolVersion = input.ReadInt32();
            break;
          }
          case 18: {
            if (encryptionRequest_ == null) {
              EncryptionRequest = new global::Neon.Rpc.Messages.Proto.EncryptionRequestProto();
            }
            input.ReadMessage(EncryptionRequest);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ProtocolVersion = input.ReadInt32();
            break;
          }
          case 18: {
            if (encryptionRequest_ == null) {
              EncryptionRequest = new global::Neon.Rpc.Messages.Proto.EncryptionRequestProto();
            }
            input.ReadMessage(EncryptionRequest);
            break;
          }
        }
      }
    }
    #endif

  }

  internal sealed partial class RpcHandshakeResponseProto : pb::IMessage<RpcHandshakeResponseProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RpcHandshakeResponseProto> _parser = new pb::MessageParser<RpcHandshakeResponseProto>(() => new RpcHandshakeResponseProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RpcHandshakeResponseProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Rpc.Messages.Proto.RpcHandshakeReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RpcHandshakeResponseProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RpcHandshakeResponseProto(RpcHandshakeResponseProto other) : this() {
      encryptionResponse_ = other.encryptionResponse_ != null ? other.encryptionResponse_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RpcHandshakeResponseProto Clone() {
      return new RpcHandshakeResponseProto(this);
    }

    /// <summary>Field number for the "encryption_response" field.</summary>
    public const int EncryptionResponseFieldNumber = 1;
    private global::Neon.Rpc.Messages.Proto.EncryptionResponseProto encryptionResponse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Neon.Rpc.Messages.Proto.EncryptionResponseProto EncryptionResponse {
      get { return encryptionResponse_; }
      set {
        encryptionResponse_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RpcHandshakeResponseProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RpcHandshakeResponseProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(EncryptionResponse, other.EncryptionResponse)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (encryptionResponse_ != null) hash ^= EncryptionResponse.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (encryptionResponse_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(EncryptionResponse);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (encryptionResponse_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(EncryptionResponse);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (encryptionResponse_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EncryptionResponse);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RpcHandshakeResponseProto other) {
      if (other == null) {
        return;
      }
      if (other.encryptionResponse_ != null) {
        if (encryptionResponse_ == null) {
          EncryptionResponse = new global::Neon.Rpc.Messages.Proto.EncryptionResponseProto();
        }
        EncryptionResponse.MergeFrom(other.EncryptionResponse);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (encryptionResponse_ == null) {
              EncryptionResponse = new global::Neon.Rpc.Messages.Proto.EncryptionResponseProto();
            }
            input.ReadMessage(EncryptionResponse);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (encryptionResponse_ == null) {
              EncryptionResponse = new global::Neon.Rpc.Messages.Proto.EncryptionResponseProto();
            }
            input.ReadMessage(EncryptionResponse);
            break;
          }
        }
      }
    }
    #endif

  }

  internal sealed partial class EncryptionRequestProto : pb::IMessage<EncryptionRequestProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EncryptionRequestProto> _parser = new pb::MessageParser<EncryptionRequestProto>(() => new EncryptionRequestProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EncryptionRequestProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Rpc.Messages.Proto.RpcHandshakeReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EncryptionRequestProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EncryptionRequestProto(EncryptionRequestProto other) : this() {
      encryptionAlgorithm_ = other.encryptionAlgorithm_;
      keyExchangeAlgorithm_ = other.keyExchangeAlgorithm_;
      clientKeyData_ = other.clientKeyData_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EncryptionRequestProto Clone() {
      return new EncryptionRequestProto(this);
    }

    /// <summary>Field number for the "encryption_algorithm" field.</summary>
    public const int EncryptionAlgorithmFieldNumber = 1;
    private string encryptionAlgorithm_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EncryptionAlgorithm {
      get { return encryptionAlgorithm_; }
      set {
        encryptionAlgorithm_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "key_exchange_algorithm" field.</summary>
    public const int KeyExchangeAlgorithmFieldNumber = 2;
    private string keyExchangeAlgorithm_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string KeyExchangeAlgorithm {
      get { return keyExchangeAlgorithm_; }
      set {
        keyExchangeAlgorithm_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "client_key_data" field.</summary>
    public const int ClientKeyDataFieldNumber = 3;
    private pb::ByteString clientKeyData_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString ClientKeyData {
      get { return clientKeyData_; }
      set {
        clientKeyData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EncryptionRequestProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EncryptionRequestProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EncryptionAlgorithm != other.EncryptionAlgorithm) return false;
      if (KeyExchangeAlgorithm != other.KeyExchangeAlgorithm) return false;
      if (ClientKeyData != other.ClientKeyData) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EncryptionAlgorithm.Length != 0) hash ^= EncryptionAlgorithm.GetHashCode();
      if (KeyExchangeAlgorithm.Length != 0) hash ^= KeyExchangeAlgorithm.GetHashCode();
      if (ClientKeyData.Length != 0) hash ^= ClientKeyData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EncryptionAlgorithm.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EncryptionAlgorithm);
      }
      if (KeyExchangeAlgorithm.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(KeyExchangeAlgorithm);
      }
      if (ClientKeyData.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(ClientKeyData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EncryptionAlgorithm.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EncryptionAlgorithm);
      }
      if (KeyExchangeAlgorithm.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(KeyExchangeAlgorithm);
      }
      if (ClientKeyData.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(ClientKeyData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EncryptionAlgorithm.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EncryptionAlgorithm);
      }
      if (KeyExchangeAlgorithm.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(KeyExchangeAlgorithm);
      }
      if (ClientKeyData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ClientKeyData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EncryptionRequestProto other) {
      if (other == null) {
        return;
      }
      if (other.EncryptionAlgorithm.Length != 0) {
        EncryptionAlgorithm = other.EncryptionAlgorithm;
      }
      if (other.KeyExchangeAlgorithm.Length != 0) {
        KeyExchangeAlgorithm = other.KeyExchangeAlgorithm;
      }
      if (other.ClientKeyData.Length != 0) {
        ClientKeyData = other.ClientKeyData;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            EncryptionAlgorithm = input.ReadString();
            break;
          }
          case 18: {
            KeyExchangeAlgorithm = input.ReadString();
            break;
          }
          case 26: {
            ClientKeyData = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            EncryptionAlgorithm = input.ReadString();
            break;
          }
          case 18: {
            KeyExchangeAlgorithm = input.ReadString();
            break;
          }
          case 26: {
            ClientKeyData = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  internal sealed partial class EncryptionResponseProto : pb::IMessage<EncryptionResponseProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EncryptionResponseProto> _parser = new pb::MessageParser<EncryptionResponseProto>(() => new EncryptionResponseProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EncryptionResponseProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Rpc.Messages.Proto.RpcHandshakeReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EncryptionResponseProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EncryptionResponseProto(EncryptionResponseProto other) : this() {
      serverKeyData_ = other.serverKeyData_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EncryptionResponseProto Clone() {
      return new EncryptionResponseProto(this);
    }

    /// <summary>Field number for the "server_key_data" field.</summary>
    public const int ServerKeyDataFieldNumber = 1;
    private pb::ByteString serverKeyData_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString ServerKeyData {
      get { return serverKeyData_; }
      set {
        serverKeyData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EncryptionResponseProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EncryptionResponseProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ServerKeyData != other.ServerKeyData) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ServerKeyData.Length != 0) hash ^= ServerKeyData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ServerKeyData.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(ServerKeyData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ServerKeyData.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(ServerKeyData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ServerKeyData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ServerKeyData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EncryptionResponseProto other) {
      if (other == null) {
        return;
      }
      if (other.ServerKeyData.Length != 0) {
        ServerKeyData = other.ServerKeyData;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ServerKeyData = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ServerKeyData = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
