// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: rpc_message_header_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Neon.Rpc.Messages.Proto {

  /// <summary>Holder for reflection information generated from rpc_message_header_data.proto</summary>
  internal static partial class RpcMessageHeaderDataReflection {

    #region Descriptor
    /// <summary>File descriptor for rpc_message_header_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RpcMessageHeaderDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1ycGNfbWVzc2FnZV9oZWFkZXJfZGF0YS5wcm90bxIIbmVvbi5ycGMaKXJw",
            "Y19tZXNzYWdlX2hlYWRlcl9kYXRhX3JwY19yZXF1ZXN0LnByb3RvGipycGNf",
            "bWVzc2FnZV9oZWFkZXJfZGF0YV9ycGNfcmVzcG9uc2UucHJvdG8iuQEKGVJw",
            "Y01lc3NhZ2VIZWFkZXJEYXRhUHJvdG8SRAoLcnBjX3JlcXVlc3QYASABKAsy",
            "LS5uZW9uLnJwYy5ScGNNZXNzYWdlSGVhZGVyRGF0YVJwY1JlcXVlc3RQcm90",
            "b0gAEkYKDHJwY19yZXNwb25zZRgCIAEoCzIuLm5lb24ucnBjLlJwY01lc3Nh",
            "Z2VIZWFkZXJEYXRhUnBjUmVzcG9uc2VQcm90b0gAQg4KDG1lc3NhZ2VfdHlw",
            "ZUIaqgIXTmVvbi5ScGMuTWVzc2FnZXMuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Neon.Rpc.Messages.Proto.RpcMessageHeaderDataRpcRequestReflection.Descriptor, global::Neon.Rpc.Messages.Proto.RpcMessageHeaderDataRpcResponseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Rpc.Messages.Proto.RpcMessageHeaderDataProto), global::Neon.Rpc.Messages.Proto.RpcMessageHeaderDataProto.Parser, new[]{ "RpcRequest", "RpcResponse" }, new[]{ "MessageType" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  internal sealed partial class RpcMessageHeaderDataProto : pb::IMessage<RpcMessageHeaderDataProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RpcMessageHeaderDataProto> _parser = new pb::MessageParser<RpcMessageHeaderDataProto>(() => new RpcMessageHeaderDataProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RpcMessageHeaderDataProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Rpc.Messages.Proto.RpcMessageHeaderDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RpcMessageHeaderDataProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RpcMessageHeaderDataProto(RpcMessageHeaderDataProto other) : this() {
      switch (other.MessageTypeCase) {
        case MessageTypeOneofCase.RpcRequest:
          RpcRequest = other.RpcRequest.Clone();
          break;
        case MessageTypeOneofCase.RpcResponse:
          RpcResponse = other.RpcResponse.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RpcMessageHeaderDataProto Clone() {
      return new RpcMessageHeaderDataProto(this);
    }

    /// <summary>Field number for the "rpc_request" field.</summary>
    public const int RpcRequestFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Neon.Rpc.Messages.Proto.RpcMessageHeaderDataRpcRequestProto RpcRequest {
      get { return messageTypeCase_ == MessageTypeOneofCase.RpcRequest ? (global::Neon.Rpc.Messages.Proto.RpcMessageHeaderDataRpcRequestProto) messageType_ : null; }
      set {
        messageType_ = value;
        messageTypeCase_ = value == null ? MessageTypeOneofCase.None : MessageTypeOneofCase.RpcRequest;
      }
    }

    /// <summary>Field number for the "rpc_response" field.</summary>
    public const int RpcResponseFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Neon.Rpc.Messages.Proto.RpcMessageHeaderDataRpcResponseProto RpcResponse {
      get { return messageTypeCase_ == MessageTypeOneofCase.RpcResponse ? (global::Neon.Rpc.Messages.Proto.RpcMessageHeaderDataRpcResponseProto) messageType_ : null; }
      set {
        messageType_ = value;
        messageTypeCase_ = value == null ? MessageTypeOneofCase.None : MessageTypeOneofCase.RpcResponse;
      }
    }

    private object messageType_;
    /// <summary>Enum of possible cases for the "message_type" oneof.</summary>
    public enum MessageTypeOneofCase {
      None = 0,
      RpcRequest = 1,
      RpcResponse = 2,
    }
    private MessageTypeOneofCase messageTypeCase_ = MessageTypeOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageTypeOneofCase MessageTypeCase {
      get { return messageTypeCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMessageType() {
      messageTypeCase_ = MessageTypeOneofCase.None;
      messageType_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RpcMessageHeaderDataProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RpcMessageHeaderDataProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(RpcRequest, other.RpcRequest)) return false;
      if (!object.Equals(RpcResponse, other.RpcResponse)) return false;
      if (MessageTypeCase != other.MessageTypeCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (messageTypeCase_ == MessageTypeOneofCase.RpcRequest) hash ^= RpcRequest.GetHashCode();
      if (messageTypeCase_ == MessageTypeOneofCase.RpcResponse) hash ^= RpcResponse.GetHashCode();
      hash ^= (int) messageTypeCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (messageTypeCase_ == MessageTypeOneofCase.RpcRequest) {
        output.WriteRawTag(10);
        output.WriteMessage(RpcRequest);
      }
      if (messageTypeCase_ == MessageTypeOneofCase.RpcResponse) {
        output.WriteRawTag(18);
        output.WriteMessage(RpcResponse);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (messageTypeCase_ == MessageTypeOneofCase.RpcRequest) {
        output.WriteRawTag(10);
        output.WriteMessage(RpcRequest);
      }
      if (messageTypeCase_ == MessageTypeOneofCase.RpcResponse) {
        output.WriteRawTag(18);
        output.WriteMessage(RpcResponse);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (messageTypeCase_ == MessageTypeOneofCase.RpcRequest) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RpcRequest);
      }
      if (messageTypeCase_ == MessageTypeOneofCase.RpcResponse) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RpcResponse);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RpcMessageHeaderDataProto other) {
      if (other == null) {
        return;
      }
      switch (other.MessageTypeCase) {
        case MessageTypeOneofCase.RpcRequest:
          if (RpcRequest == null) {
            RpcRequest = new global::Neon.Rpc.Messages.Proto.RpcMessageHeaderDataRpcRequestProto();
          }
          RpcRequest.MergeFrom(other.RpcRequest);
          break;
        case MessageTypeOneofCase.RpcResponse:
          if (RpcResponse == null) {
            RpcResponse = new global::Neon.Rpc.Messages.Proto.RpcMessageHeaderDataRpcResponseProto();
          }
          RpcResponse.MergeFrom(other.RpcResponse);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Neon.Rpc.Messages.Proto.RpcMessageHeaderDataRpcRequestProto subBuilder = new global::Neon.Rpc.Messages.Proto.RpcMessageHeaderDataRpcRequestProto();
            if (messageTypeCase_ == MessageTypeOneofCase.RpcRequest) {
              subBuilder.MergeFrom(RpcRequest);
            }
            input.ReadMessage(subBuilder);
            RpcRequest = subBuilder;
            break;
          }
          case 18: {
            global::Neon.Rpc.Messages.Proto.RpcMessageHeaderDataRpcResponseProto subBuilder = new global::Neon.Rpc.Messages.Proto.RpcMessageHeaderDataRpcResponseProto();
            if (messageTypeCase_ == MessageTypeOneofCase.RpcResponse) {
              subBuilder.MergeFrom(RpcResponse);
            }
            input.ReadMessage(subBuilder);
            RpcResponse = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Neon.Rpc.Messages.Proto.RpcMessageHeaderDataRpcRequestProto subBuilder = new global::Neon.Rpc.Messages.Proto.RpcMessageHeaderDataRpcRequestProto();
            if (messageTypeCase_ == MessageTypeOneofCase.RpcRequest) {
              subBuilder.MergeFrom(RpcRequest);
            }
            input.ReadMessage(subBuilder);
            RpcRequest = subBuilder;
            break;
          }
          case 18: {
            global::Neon.Rpc.Messages.Proto.RpcMessageHeaderDataRpcResponseProto subBuilder = new global::Neon.Rpc.Messages.Proto.RpcMessageHeaderDataRpcResponseProto();
            if (messageTypeCase_ == MessageTypeOneofCase.RpcResponse) {
              subBuilder.MergeFrom(RpcResponse);
            }
            input.ReadMessage(subBuilder);
            RpcResponse = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
